origincert: /etc/cloudflared/cert.pem
tunnel: 55315a14-839b-4872-a867-d3956c839e11
credentials-file: /etc/cloudflared/55315a14-839b-4872-a867-d3956c839e11.json

ingress:
  - hostname: n8n.szymonpaluch.com
    service: http://n8n:5678
  - service: http_status:404
